---
- name: Create dotnet directory
  file:
    path: "/usr/share/dotnet"
    state: directory
  become: yes

- name: Install dotnet 8
  ansible.builtin.unarchive:
    src: https://download.visualstudio.microsoft.com/download/pr/0a1b3cbd-b4af-4d0d-9ed7-0054f0e200b4/4bcc533c66379caaa91770236667aacb/dotnet-sdk-8.0.204-linux-x64.tar.gz
    dest: "/usr/share/dotnet"
    remote_src: yes
  become: yes

# The below is for omnisharp in VS Code
- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/share/dotnet/dotnet
    dest: /usr/local/bin/dotnet
    owner: root
    group: root
    state: link
  become: yes

- name: Install dotnet tool dotnet-ef
  shell: dotnet tool install --global dotnet-ef
  ignore_errors: true

- name: Install dotnet tool dotnet-reportgenerator-globaltool
  shell: dotnet tool install --global dotnet-reportgenerator-globaltool
  ignore_errors: true
