---
- name: Create .ssh directory
  file:
    path: "/usr/share/dotnet"
    state: directory
  become: yes

- name: Install dotnet 7
  ansible.builtin.unarchive:
    src: https://download.visualstudio.microsoft.com/download/pr/c646b288-5d5b-4c9c-a95b-e1fad1c0d95d/e13d71d48b629fe3a85f5676deb09e2d/dotnet-sdk-7.0.102-linux-x64.tar.gz
    dest: "/usr/share/dotnet"
    remote_src: yes
  become: yes
