---
- name: Download
  get_url:
    dest: /tmp/dotnet-install.sh
    mode: 0755
    url: https://dot.net/v1/dotnet-install.sh

- name: Install SDK
  shell: /tmp/dotnet-install.sh -c 6.0

- name: Install Runtime
  shell: /tmp/dotnet-install.sh -c 6.0 --runtime aspnetcore

- name: Remove Installation Script
  file:
    path: /tmp/dotnet-install.sh
    state: absent
