---
- name: Download
  get_url:
    dest: /tmp/packages-microsoft-prod.deb
    mode: 0755
    url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb

- name: Install a .deb package
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb
  become: yes

- name: Remove Installation zip
  file:
    path: /tmp/packages-microsoft-prod.deb
    state: absent

- name: Install dotnet 7
  ansible.builtin.package:
    name:
      - dotnet-sdk-7.0
      - aspnetcore-runtime-7.0
    state: latest
    update_cache: yes
  become: yes
