---
- name: Download
  get_url:
    dest: /tmp/k9s.tar.gz
    mode: 0755
    url: https://github.com/derailed/k9s/releases/download/v0.27.0/k9s_Linux_amd64.tar.gz

- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/k9s.tar.gz
    dest: /usr/local/bin
  become: yes

- name: Remove Installation zip
  file:
    path: /tmp/k9s.tar.gz
    state: absent

- name: Directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/k9s"
    state: directory

- name: skin.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/k9s/skin.yml"
    src: "skin.yml"
