---
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

- name: Install node
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/lts"
