---
- hosts: localhost
  connection: local
  tasks:
    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items:
        - git
        - fonts
        - nnn
        - neovim
        - zsh
        - oh-my-zsh
        - go
        - dotnet
        - ripgrep
        - kind
        - k9s
        - pulumi
        - nvm
        - pnpm
        - jq
        - oh-my-tmux
      tags:
        - always
