---
- hosts: localhost
  connection: local
  tasks:
    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items:
        - git
        - fonts
        - kitty
        - neovim
        - zsh
        - oh-my-zsh
      tags:
        - always
