---
- hosts: localhost
  connection: local
  tasks:
    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items:
        - system
        - git
        - fonts
        - nnn
        - ssh
        - go
        - dotnet
        - ripgrep
        - kind
        - k9s
        - azure-cli
        - k6
        - cloudflared
        - pulumi
        - terraform
        - nvm
        - pnpm
        - jq
        - snyk
        - oh-my-tmux
        - zsh
        - kubeseal
        - kustomize
        - oh-my-zsh
      tags:
        - always
