---
- name: Check Existing Installation
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: install

- name: Download
  get_url:
    dest: /tmp/ohmyzsh-install.sh
    mode: 0755
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  when: not install.stat.exists

- name: Install
  shell: /tmp/ohmyzsh-install.sh
  when: not install.stat.exists

- name: Remove Installation Script
  file:
    path: /tmp/ohmyzsh-install.sh
    state: absent

- name: Copy .zshrc
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: .zshrc.j2

- name: Install zplug
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zplug"
    repo: https://github.com/zplug/zplug
    single_branch: yes
    update: yes
    version: master
