---
- name: Go Version
  set_fact:
    version: 1.20.3

- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true

- name: Download
  get_url:
    dest: /tmp/go.tar.gz
    mode: 0755
    url: "https://go.dev/dl/go{{ version }}.linux-amd64.tar.gz"
    checksum: "sha256:979694c2c25c735755bf26f4f45e19e64e4811d661dd07b8c010f7a8e18adfca"
    force: no
    use_proxy: yes
    validate_certs: yes
  when: '"1.20.3" not in result.stdout'

- name: Delete Go directory
  file:
    path: /usr/local/go
    state: absent
  become: yes
  when: '"1.20.3" not in result.stdout'

- name: Go directory
  file:
    path: /usr/local/go
    state: directory
  become: yes
  when: '"1.20.3" not in result.stdout'

- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
  become: yes
  when: '"1.20.3" not in result.stdout'

- name: Remove Installation zip
  file:
    path: /tmp/go.tar.gz
    state: absent
  when: '"1.20.3" not in result.stdout'
