---
- name: Download
  get_url:
    dest: /tmp/go.tar.gz
    mode: 0755
    url: https://go.dev/dl/go1.19.linux-amd64.tar.gz

- name: Go directory
  file:
    path: /usr/local/go
    state: directory
  become: yes

- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
  become: yes

- name: Remove Installation zip
  file:
    path: /tmp/go.tar.gz
    state: absent