---
- name: Create terraform tmp directory
  file:
    path: /tmp/terraform
    state: directory
  become: yes

- name: Download terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip
    dest: /tmp/terraform
    remote_src: yes
  become: yes

- name: Copy file
  ansible.builtin.copy:
    src: /tmp/terraform/terraform
    dest: /usr/local/bin/terraform
    mode: 0755
  become: yes

- name: Remove Installation
  ansible.builtin.file:
    path: /tmp/terraform
    state: absent
  become: yes
